/// # PersistenceAdapter
///
/// ## What it does
/// Abstraction layer for database operations. Allows swapping persistence
/// backends (ObjectBox, IndexedDB) without changing repository code.
///
/// ## What it enables
/// - ObjectBox on native platforms (Android, iOS, desktop)
/// - IndexedDB on web
/// - Same EntityRepository code works with both
/// - Each implementation handles vector search its own way
///
/// ## Usage
/// ```dart
/// // Native platforms
/// final adapter = ObjectBoxNoteAdapter(store);
/// final repo = NoteRepository(adapter: adapter);
///
/// // Web
/// final adapter = IndexedDBNoteAdapter(database);
/// final repo = NoteRepository(adapter: adapter);
///
/// // Repository API unchanged
/// await repo.save(note);
/// final results = await repo.semanticSearch('query');
/// ```

import '../base_entity.dart';

/// Core persistence operations for entities.
///
/// Each entity type needs its own adapter implementation because:
/// 1. ObjectBox uses codegen with entity-specific Box<T>
/// 2. Query methods vary by entity fields
/// 3. Vector search configuration is entity-specific
abstract class PersistenceAdapter<T extends BaseEntity> {
  // ============ CRUD ============

  /// Find entity by internal database ID.
  /// Returns null if not found.
  Future<T?> findById(int id);

  /// Find entity by UUID (universal identifier).
  /// Returns null if not found.
  /// Implementations should use an index for O(1) lookup.
  Future<T?> findByUuid(String uuid);

  /// Get all entities of this type.
  Future<List<T>> findAll();

  /// Save entity (insert if new, update if exists).
  /// Returns the entity with id assigned.
  ///
  /// For Embeddable entities: indexes the embedding if present.
  /// The adapter handles both document storage and vector indexing.
  Future<T> save(T entity);

  /// Batch save multiple entities.
  /// Returns entities with ids assigned.
  Future<List<T>> saveAll(List<T> entities);

  /// Delete entity by internal database ID.
  /// Returns true if entity was deleted, false if not found.
  /// Also removes from vector index if applicable.
  Future<bool> delete(int id);

  /// Delete entity by UUID.
  /// Returns true if entity was deleted, false if not found.
  /// Also removes from vector index if applicable.
  Future<bool> deleteByUuid(String uuid);

  /// Batch delete entities by internal IDs.
  /// Also removes from vector index if applicable.
  Future<void> deleteAll(List<int> ids);

  // ============ Queries ============

  /// Find entities pending sync (syncStatus == SyncStatus.local).
  /// Used by sync service to push local changes to remote.
  Future<List<T>> findUnsynced();

  /// Count of all entities.
  Future<int> count();

  // ============ Semantic Search ============

  /// Search entities by vector similarity.
  ///
  /// [queryVector] - Embedding of the search query (generated by caller)
  /// [limit] - Maximum results to return
  /// [minSimilarity] - Minimum similarity threshold (0.0 to 1.0)
  ///
  /// Returns entities sorted by descending similarity.
  ///
  /// Implementation varies:
  /// - ObjectBox: Native HNSW via nearestNeighbors query
  /// - IndexedDB: Separate local_hnsw index + document lookup
  Future<List<T>> semanticSearch(
    List<double> queryVector, {
    int limit = 10,
    double minSimilarity = 0.0,
  });

  /// Number of vectors currently in the search index.
  /// Returns 0 if entity type doesn't support embeddings.
  int get indexSize;

  /// Rebuild the vector index from all stored entities.
  ///
  /// [generateEmbedding] - Callback to generate embedding for entities
  /// that have null embeddings. This allows the adapter to request
  /// embedding generation without depending on EmbeddingService.
  ///
  /// Use when:
  /// - Index is missing or corrupt
  /// - Migrating from another storage backend
  /// - Recovering from failed sync
  Future<void> rebuildIndex(
    Future<List<double>?> Function(T entity) generateEmbedding,
  );

  // ============ Lifecycle ============

  /// Close the adapter and release resources.
  /// Call when the repository is no longer needed.
  Future<void> close();
}
