mod frb_generated; /* AUTO INJECTED BY flutter_rust_bridge. This line may not be accurate, and you can change it according to your needs. */
/// # Everything Stack Native Bridge
///
/// Rust FFI implementation for cross-platform native functionality.
/// Replaces dart:io for WebSocket communication on Windows (and all native platforms).
///
/// ## Architecture
/// - Tokio runtime: Single global, lazy-initialized
/// - Connection registry: Rust owns WebSocket connections, Dart gets handles
/// - StreamSink: Receive streams pushed from Rust to Dart
///
/// ## Modules
/// - `api`: Public FFI interface (auto-generated by flutter_rust_bridge)
/// - `runtime`: Global Tokio runtime management
/// - `transport`: WebSocket transport implementation

pub mod api;
pub mod runtime;
pub mod transport;

/// Initialize the native bridge.
/// Must be called before any other FFI functions.
pub fn init() {
    // Ensure runtime is initialized
    runtime::ensure_runtime();
}

/// Simple hello world to test FFI bridge.
pub fn hello_world() -> String {
    "Hello from Rust! WebSocket transport ready.".to_string()
}
