// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Test function to verify FFI bridge works.
Future<String> helloFromRust() => RustLib.instance.api.crateApiHelloFromRust();

/// Connect to WebSocket server.
///
/// ## Arguments
/// - `url`: Full WebSocket URL (ws:// or wss://)
/// - `headers`: Optional HTTP headers for handshake
/// - `subprotocols`: Optional WebSocket subprotocols (for Sec-WebSocket-Protocol)
///
/// ## Returns
/// - Connection handle (u64) on success
/// - Error string on failure
Future<BigInt> websocketConnect(
        {required String url,
        required List<(String, String)> headers,
        required List<String> subprotocols}) =>
    RustLib.instance.api.crateApiWebsocketConnect(
        url: url, headers: headers, subprotocols: subprotocols);

/// Send binary data to WebSocket.
///
/// ## Arguments
/// - `handle`: Connection handle from `websocket_connect()`
/// - `data`: Bytes to send
///
/// ## Returns
/// - Ok(()) on success
/// - Err(msg) if connection not found or send failed
Future<void> websocketSend({required BigInt handle, required List<int> data}) =>
    RustLib.instance.api.crateApiWebsocketSend(handle: handle, data: data);

/// Close WebSocket connection gracefully.
///
/// ## Arguments
/// - `handle`: Connection handle to close
Future<void> websocketClose({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketClose(handle: handle);

/// Dispose WebSocket connection and free resources.
///
/// ## Arguments
/// - `handle`: Connection handle to dispose
Future<void> websocketDispose({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketDispose(handle: handle);

/// Get connection state as string (for debugging).
Future<String> websocketState({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketState(handle: handle);

/// Start receiving messages from WebSocket.
///
/// Spawns a background task that reads from the WebSocket and queues messages.
/// Call `websocket_poll_receive()` to retrieve queued messages.
///
/// ## Important
/// - Must be called after `websocket_connect()`
/// - Can only be called once per connection
Future<void> websocketStartReceive({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketStartReceive(handle: handle);

/// Poll for received messages.
///
/// Returns all queued messages since last poll and clears the queue.
///
/// ## Arguments
/// - `handle`: Connection handle
///
/// ## Returns
/// - Vec of message byte arrays (may be empty if no messages)
Future<List<Uint8List>> websocketPollReceive({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketPollReceive(handle: handle);
