// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Test function to verify FFI bridge works.
Future<String> helloFromRust() => RustLib.instance.api.crateApiHelloFromRust();

/// Connect to WebSocket server.
///
/// ## Arguments
/// - `url`: Full WebSocket URL (ws:// or wss://)
/// - `headers`: Optional HTTP headers for handshake
///
/// ## Returns
/// - Connection handle (u64) on success
/// - Error string on failure
Future<BigInt> websocketConnect(
        {required String url, required List<(String, String)> headers}) =>
    RustLib.instance.api.crateApiWebsocketConnect(url: url, headers: headers);

/// Send binary data to WebSocket.
///
/// ## Arguments
/// - `handle`: Connection handle from `websocket_connect()`
/// - `data`: Bytes to send
///
/// ## Returns
/// - Ok(()) on success
/// - Err(msg) if connection not found or send failed
Future<void> websocketSend({required BigInt handle, required List<int> data}) =>
    RustLib.instance.api.crateApiWebsocketSend(handle: handle, data: data);

/// Close WebSocket connection gracefully.
///
/// ## Arguments
/// - `handle`: Connection handle to close
Future<void> websocketClose({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketClose(handle: handle);

/// Dispose WebSocket connection and free resources.
///
/// ## Arguments
/// - `handle`: Connection handle to dispose
Future<void> websocketDispose({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketDispose(handle: handle);

/// Get connection state as string (for debugging).
Future<String> websocketState({required BigInt handle}) =>
    RustLib.instance.api.crateApiWebsocketState(handle: handle);
